### PR TITLE
Make `ApnsClient#sendNotification` generic (closes #342)

### LINKED ISSUE #342: Question: Why does `ApnsClient` have to be generic?
Maybe I'm misunderstanding `ApnsClient`. I've only coded in it for maybe 30 minutes, so I might be wrong!

Above said, I noticed that it uses generics and introduces `T extends ApnsPushNotification`. From the perspective of polymorphism this means that an instance of the class can't be used with different implementations of `ApnsPushNotification`. Is this really a deliberate decision? Proposal here is to make the individual methods generic, not the whole class in itself. That is, replacing with

    public Future<PushNotificationResponse<T>> sendNotification(final T notification)

with

    public <T extends ApnsPushNotification> Future<PushNotificationResponse<T>> sendNotification(final T notification)

. What do you think of this? Doable?

### PR DESCRIPTION
**Pull request by jchambers**
As suggested in #342, this change makes the `ApnsClient` class non-generic, but instead makes its `sendNotification` method generic. This makes an `ApnsClient` much more flexible in terms of the types of notifications it can handle, which is definitely a good thing. This does come with some costs, though:

1. There's some API breakage. Good thing we have a big "we may change the API before 1.0" disclaimer at the bottom of the README ;)
2. The sending code itself is incrementally more complex.
3. We have an additional listener in the cycle for each notification we send, which causes some slight (~1%) performance decreases as shown below:

```
# Before

(flushImmediately)  (notificationCount)  Mode  Cnt  Score   Error  Units
              true                10000    ss   40  0.632 ± 0.022   s/op
             false                10000    ss   40  0.606 ± 0.018   s/op

# After

(flushImmediately)  (notificationCount)  Mode  Cnt  Score   Error  Units
              true                10000    ss   40  0.640 ± 0.017   s/op
             false                10000    ss   40  0.615 ± 0.020   s/op
```

In all, I think the tradeoff is worth it, but would very much appreciate other perspectives.

----

TODO:

- [x] Update inline docs
- [x] Update README

### CODE REVIEW

File: pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientBuilder.java [hunk 1]
```diff
@@ -393,7 +393,7 @@
      *
      * @since 0.8
      */
-    public ApnsClient<T> build() throws SSLException {
+    public ApnsClient build() throws SSLException {
```
Comment (panchenko) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientBuilder.java]: probably the whole ApnsClientBuilder class should not be generic.

File: pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java [hunk 2]
```diff
@@ -103,7 +103,7 @@
  *
  * @since 0.5
  */
-public class ApnsClient<T extends ApnsPushNotification> {
+public class ApnsClient {
```
Comment (panchenko) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java]: `<T>` should be removed from the class javadoc too.

**Comment by panchenko** [comment]
@jchambers I think it is not necessary to have that additional listener, `SimplePushNotificationResponse` could be created directly, as after type erasure it is aware only of `ApnsPushNotification`.

File: pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientBuilder.java (hunk 1 above)
Comment (jchambers) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientBuilder.java]: Good catch! Done in a4c4957.

File: pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java (hunk 2 above)
Comment (jchambers) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java]: Agreed—I'll be making a comprehensive pass at the docs shortly.

**Comment by jchambers** [comment]
> I think it is not necessary to have that additional listener

I kept thinking the same thing when I was working on this, but kept struggling to make it work out in the end. Can you be more specific with your suggestion? I'm totally willing to believe (and strongly suspect) that I've missed something obvious.

**Comment by panchenko** [comment]
> Can you be more specific with your suggestion?

I am thinking of having declaration like this:

`private final Map<ApnsPushNotification, Promise<PushNotificationResponse<ApnsPushNotification>>> responsePromises`

and the only cast needed is in `sendNotification()` when adding the new promise there.

**Comment by jchambers** [comment]
@panchenko That was pretty much my thought, too. Ultimately, we have to do something like this:

```java
ApnsClient.this.responsePromises.put(notification, (Promise<PushNotificationResponse<ApnsPushNotification>>) responsePromise);
```

…but then the compiler complains:

> Cannot cast from `Promise<PushNotificationResponse<T>>` to `Promise<PushNotificationResponse<ApnsPushNotification>>`

…and that's the part I haven't quite figured out yet. I'm not sure why we can't make that cast; it seems like we know that, by definition, `T extends ApnsPushNotification`. I'll admit that I haven't yet sat down with a pen and paper to work out the erasure implications, but this seems to be the fundamental limitation here.

**Comment by jchambers** [comment]
Good call. When in doubt, be vague ;)

Done in e0698cd, and I think that helps things quite a bit.

File: pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java [hunk 3]
```diff
@@ -493,8 +492,8 @@ public void run() {
 
                                 @Override
                                 public void run() {
-                                    for (final Promise<PushNotificationResponse<T>> responsePromise : ApnsClient.this.responsePromises.values()) {
-                                        responsePromise.tryFailure(new ClientNotConnectedException("Client disconnected unexpectedly."));
+                                    for (final Promise<PushNotificationResponse<ApnsPushNotification>> partialResponsePromise : ApnsClient.this.responsePromises.values()) {
+                                        partialResponsePromise.tryFailure(new ClientNotConnectedException("Client disconnected unexpectedly."));
```
Comment (panchenko) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java]: I would suggest renaming `partialResponsePromise` back to `responsePromise` here.

Comment (jchambers) [inline pushy/src/main/java/com/relayrides/pushy/apns/ApnsClient.java]: Good catch—got it in 75c9fe6.
